# # RGBD Camera configuration
# - ros_topic_name: "cam_1/color/camera_info"
#   gz_topic_name: "{prefix}/cam_1/camera_info"
#   ros_type_name: "sensor_msgs/msg/CameraInfo"
#   gz_type_name: "gz.msgs.CameraInfo"
#   direction: GZ_TO_ROS
#   lazy: true

# - ros_topic_name: "cam_1/depth/color/points"
#   gz_topic_name: "{prefix}/cam_1/points"
#   ros_type_name: "sensor_msgs/msg/PointCloud2"
#   gz_type_name: "gz.msgs.PointCloudPacked"
#   direction: GZ_TO_ROS
#   lazy: true

# # Vacuum Gripper Control (Service Bridge)
# - ros_topic_name: "{prefix}/vacuum_gripper/enable"
#   gz_topic_name: "/model/{model_name}/link/{prefix}vac_gripper/vacuum_gripper/enable"
#   ros_type_name: "std_srvs/srv/SetBool"
#   gz_type_name: "gz.msgs.Boolean"
#   direction: BIDIRECTIONAL

# # Vacuum Gripper Status
# - ros_topic_name: "{prefix}/vacuum_gripper/suction_on"
#   gz_topic_name: "/model/{model_name}/link/{prefix}vac_gripper/vacuum_gripper/suction_on"
#   ros_type_name: "std_msgs/msg/Bool"
#   gz_type_name: "gz.msgs.Boolean"
#   direction: BIDIRECTIONAL
#   lazy: false

# LIDAR configuration
- ros_topic_name: "scan"
  gz_topic_name: "{prefix}/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS
  lazy: false

# IMU configuration
- ros_topic_name: "imu/data"
  gz_topic_name: "{prefix}/imu/data"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS
  lazy: false

# Sending velocity commands from ROS 2 to Gazebo
- ros_topic_name: "diff_drive_controller/cmd_vel"
  gz_topic_name: "{prefix}/diff_drive_controller/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: BIDIRECTIONAL
  lazy: false

# # Odometry (if your OdometryPublisher or drive plugin publishes it)
# - ros_topic_name: "odom"
#   gz_topic_name: "{prefix}/odom"
#   ros_type_name: "nav_msgs/msg/Odometry"
#   gz_type_name: "gz.msgs.Odometry"
#   direction: GZ_TO_ROS
#   lazy: false

# # Odometry with covariance (if your OdometryPublisher or drive plugin publishes it)
# - ros_topic_name: "odometry_with_covariance"
#   gz_topic_name: "{prefix}/odometry_with_covariance"
#   ros_type_name: "nav_msgs/msg/Odometry"
#   gz_type_name: "gz.msgs.Odometry"
#   direction: GZ_TO_ROS
#   lazy: false


# # Joint state bridge
# - ros_topic_name: "joint_states"
#   gz_topic_name: "{prefix}/joint_states"
#   ros_type_name: "sensor_msgs/msg/JointState"
#   gz_type_name: "gz.msgs.Model"
#   direction: GZ_TO_ROS
#   lazy: false

# # TF bridge (Gazebo â†’ ROS 2)
# - ros_topic_name: "tf"
#   gz_topic_name: "tf"
#   ros_type_name: "tf2_msgs/msg/TFMessage"
#   gz_type_name: "gz.msgs.Pose_V"
#   direction: GZ_TO_ROS
#   lazy: false

# # Clock configuration
# - ros_topic_name: "clock"
#   gz_topic_name: "clock"
#   ros_type_name: "rosgraph_msgs/msg/Clock"
#   gz_type_name: "gz.msgs.Clock"
#   direction: GZ_TO_ROS
#   lazy: false